language: r
r:
- oldrel
- release
- devel
install:
- Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'
- Rscript -e 'devtools::install_cran("data.table")'
- Rscript -e 'devtools::install_cran("ggplot2")'
- Rscript -e 'devtools::install_cran("knitr")'
- Rscript -e 'devtools::install_cran("reshape2")'
- Rscript -e 'devtools::install_cran("rmarkdown")'
- Rscript -e 'devtools::install_cran("qwraps2")'
script:
- make check
